In [ ]:
import pandas as pd

1) Carregue a planilha "world_cup_results" em um DataFrame Pandas

In [ ]:
jogos = pd.read_excel('/content/jogos.xlsx')

In [ ]:
2) Conte quantos jogos cada pais fez em copas do mundo.

In [ ]:
jogos_casa = jogos['HomeTeam'].value_counts()
jogos_visitante = jogos['AwayTeam'].value_counts()
jogos_total = jogos_casa + jogos_visitante
print(jogos_total)

Algeria                 14.0
Angola                   3.0
Argentina               81.0
Australia               13.0
Austria                 29.0
                        ...
United Arab Emirates     3.0
Uruguay                 52.0
Wales                    5.0
Yugoslavia              37.0
Zaire                    3.0
Length: 83, dtype: float64

3) Mostre apenas os jogos das finais;

In [ ]:
jogos.loc[jogos['Round'] == 'Final']

,Year,Date,Time,Round,Stadium,City,Country,HomeTeam,HomeGoals,AwayGoals,AwayTeam,Observation
17,1930,1930-07-30,14:15,Final,Estadio Centenario,Montevideo,Uruguay,Uruguay,4,2,Argentina,
34,1934,1934-06-10,17:30,Final,Nazionale PNF,Rome,Italy,Italy,2,1,Czechoslovakia,Italy win after extra time
52,1938,1938-06-19,17:00,Final,Stade Olympique,Colombes,France,Italy,4,2,Hungary,
100,1954,1954-07-04,17:00,Final,Wankdorf Stadium,Berne,Switzerland,Germany FR,3,2,Hungary,
135,1958,1958-06-29,15:00,Final,Rasunda Stadium,Solna,Sweden,Brazil,5,2,Sweden,
167,1962,1962-06-17,14:30,Final,Nacional,Santiago De Chile,Chile,Brazil,3,1,Czechoslovakia,
199,1966,1966-07-30,15:00,Final,Wembley Stadium,London,England,England,4,2,Germany FR,England win after extra time
231,1970,1970-06-21,12:00,Final,Estadio Azteca,Mexico City,Mexico,Brazil,4,1,Italy,
269,1974,1974-07-07,16:00,Final,Olympiastadion,Munich,Germany,Netherlands,1,2,Germany FR,
307,1978,1978-06-25,15:00,Final,El Monumental - Estadio Monumental Antonio Ves...,Buenos Aires,Argentina,Argentina,3,1,Netherlands,Argentina win after extra time
359,1982,1982-07-11,20:00,Final,Santiago Bernabeu,Madrid,Spain,Italy,3,1,Germany FR,
411,1986,1986-06-29,12:00,Final,Estadio Azteca,Mexico City,Mexico,Argentina,3,2,Germany FR,
463,1990,1990-07-08,20:00,Final,Stadio Olimpico,Rome,Italy,Germany FR,1,0,Argentina,
515,1994,1994-07-17,12:30,Final,Rose Bowl,Los Angeles,USA,Brazil,0,0,Italy,Brazil win on penalties (3 - 2)
579,1998,1998-07-12,21:00,Final,Stade de France,Saint-Denis,France,Brazil,0,3,France,
643,2002,2002-06-30,20:00,Final,International Stadium Yokohama,Yokohama,Korea/Japan,Germany,0,2,Brazil,
707,2006,2006-07-09,20:00,Final,Olympiastadion,Berlin,Germany,Italy,1,1,France,Italy win on penalties (5 - 3)
771,2010,2010-07-11,20:30,Final,Soccer City Stadium,Johannesburg,South Africa,Netherlands,0,1,Spain,Spain win after extra time
828,2014,2014-07-13,16:00,Final,Estadio do Maracana,Rio De Janeiro,Brazil,Germany,1,0,Argentina,Germany win after extra time
851,2014,2014-07-13,16:00,Final,Estadio do Maracana,Rio De Janeiro,Brazil,Germany,1,0,Argentina,Germany win after extra time

4) Conte o total de gols que foram feitos em copas;

In [ ]:
gols_casa = jogos['HomeGoals'].sum()
gols_fora = jogos['AwayGoals'].sum()
gols_total = gols_casa + gols_fora
print(gols_casa)
print(gols_fora)
print(f' O numero total de gols foi: {gols_total}')

1543
871
 O numero total de gols foi: 2414

5) Apresente o país que fez mais gols em copas; (groupby)

In [ ]:
gols_casa = jogos[['HomeTeam', 'HomeGoals']].groupby('HomeTeam').sum()
gols_fora = jogos[['AwayTeam', 'AwayGoals']].groupby('AwayTeam').sum()
gols_total = gols_fora['AwayGoals'] + gols_casa['HomeGoals']
gols_total.fillna(0, inplace=True)
print(gols_total.sort_values().tail(1))

Brazil    225.0
dtype: float64

In [ ]:
6) Qual foi a maior goleada? abs() retorna apenas valores positivos

In [ ]:
jogos['saldo_de_gols'] = (jogos['HomeGoals'] - jogos['AwayGoals']).abs()
jogos.loc[jogos['saldo_de_gols'] == jogos['saldo_de_gols'].max()]

,Year,Date,Time,Round,Stadium,City,Country,HomeTeam,HomeGoals,AwayGoals,AwayTeam,Observation,saldo_de_gols
80,1954,1954-06-17,18:00,Group 2,Hardturm,Zurich,Switzerland,Hungary,9,0,Korea Republic,,9
243,1974,1974-06-18,19:30,Group 2,Parkstadion,Gelsenkirchen,Germany,Yugoslavia,9,0,Zaire,,9
312,1982,1982-06-15,21:00,Group 3,Nuevo Estadio,Elche,Spain,Hungary,10,1,El Salvador,,9

In [ ]:
7) Mostre o nome de todas as cidades que já receberam jogos da copa; (unique)

In [ ]:
jogos['City'].unique()

array(['Montevideo ', 'Turin ', 'Naples ', 'Milan ', 'Bologna ',
       'Florence ', 'Genoa ', 'Rome ', 'Trieste ', 'Paris ', 'Reims ',
       'Colombes ', 'Toulouse ', 'Marseilles ', 'Strasbourg ',
       'Le Havre ', 'Bordeaux ', 'Lille ', 'Antibes ', 'Rio De Janeiro ',
       'Curitiba ', 'Sao Paulo ', 'Belo Horizonte ', 'Porto Alegre ',
       'Recife ', 'Berne ', 'Zurich ', 'Geneva ', 'Lausanne ', 'Basel ',
       'Lugano ', 'Solna ', 'Gothenburg ', 'Malmï¿½ ', 'Sandviken ',
       'Norrkï¿½Ping ', 'Vasteras ', 'Udevalla ', 'Halmstad ', 'Boras ',
       'Helsingborg ', 'Eskilstuna ', 'Orebro ', 'Arica ',
       'Vina Del Mar ', 'Rancagua ', 'Santiago De Chile ', 'London ',
       'Sheffield ', 'Liverpool ', 'Middlesbrough ', 'Manchester ',
       'Birmingham ', 'Sunderland ', 'Mexico City ', 'Puebla ', 'Leon ',
       'Guadalajara ', 'Toluca ', 'Frankfurt/Main ', 'Berlin West ',
       'Hamburg ', 'Dortmund ', 'Hanover ', 'Dï¿½Sseldorf ', 'Munich ',
       'Stuttgart ', 'Gelsenkirchen ', 'Buenos Aires ', 'Mar Del Plata ',
       'Rosario ', 'Cordoba ', 'Mendoza ', 'Barcelona ', 'Vigo ',
       'Seville ', 'La Coruï¿½A ', 'Elche ', 'Malaga ', 'Gijon ',
       'Bilbao ', 'Valencia ', 'Oviedo ', 'Valladolid ', 'Zaragoza ',
       'Alicante ', 'Madrid ', 'Irapuato ', 'Monterrey ',
       'Nezahualcoyotl ', 'Queretaro ', 'Bari ', 'Cagliari ', 'Verona ',
       'Palermo ', 'Udine ', 'Dallas ', 'Chicago ', 'Detroit ',
       'New York/New Jersey ', 'Los Angeles ', 'Orlando ',
       'Washington Dc ', 'San Francisco ', 'Boston ', 'Saint-Denis ',
       'Montpellier ', 'Lens ', 'Nantes ', 'Lyon ', 'Saint-Etienne ',
       'Seoul ', 'Ulsan ', 'Niigata ', 'Sapporo ', 'Ibaraki ', 'Busan ',
       'Saitama ', 'Gwangju ', 'Kobe ', 'Suwon ', 'Daegu ', 'Jeonju ',
       'Jeju ', 'Incheon ', 'Yokohama ', 'Rifu ', 'Oita ', 'Shizuoka ',
       'Osaka ', 'Daejeon ', 'Leipzig ', 'Nuremberg ', 'Cologne ',
       'Kaiserslautern ', 'Berlin ', 'Johannesburg ', 'Cape Town ',
       'Nelson Mandela Bay/Port Elizabeth ', 'Phokeng ', 'Polokwane ',
       'Tshwane/Pretoria ', 'Durban ', 'Mangaung/Bloemfontein ',
       'Nelspruit ', 'Natal ', 'Salvador ', 'Cuiaba ', 'Fortaleza ',
       'Manaus ', 'Brasilia '], dtype=object)

8) Mostre a quantidade de jogos que foram feitos em cada cidade do mundo;

In [ ]:
jogos['City'].value_counts()

Mexico City        23
Montevideo         18
Rio De Janeiro     18
Guadalajara        17
Johannesburg       15
                   ..
Eskilstuna          1
Orebro              1
Reims               1
Antibes             1
Lille               1
Name: City, Length: 151, dtype: int64

9) Mostre as finais que tiveram participação de seleções anfitriãs;

In [ ]:
finais = jogos.loc[jogos['Round'] == 'Final']
finais1 = finais.loc[jogos['Country'] == jogos['HomeTeam']]
finais2 = finais.loc[jogos['Country'] == jogos['AwayTeam']]

In [ ]:
finais1

,Year,Date,Time,Round,Stadium,City,Country,HomeTeam,HomeGoals,AwayGoals,AwayTeam,Observation,saldo_de_gols,gols_na_partida
17,1930,1930-07-30,14:15,Final,Estadio Centenario,Montevideo,Uruguay,Uruguay,4,2,Argentina,,2,6
34,1934,1934-06-10,17:30,Final,Nazionale PNF,Rome,Italy,Italy,2,1,Czechoslovakia,Italy win after extra time,1,3
199,1966,1966-07-30,15:00,Final,Wembley Stadium,London,England,England,4,2,Germany FR,England win after extra time,2,6
307,1978,1978-06-25,15:00,Final,El Monumental - Estadio Monumental Antonio Ves...,Buenos Aires,Argentina,Argentina,3,1,Netherlands,Argentina win after extra time,2,4

In [ ]:
finais2

,Year,Date,Time,Round,Stadium,City,Country,HomeTeam,HomeGoals,AwayGoals,AwayTeam,Observation,saldo_de_gols,gols_na_partida
135,1958,1958-06-29,15:00,Final,Rasunda Stadium,Solna,Sweden,Brazil,5,2,Sweden,,3,7
579,1998,1998-07-12,21:00,Final,Stade de France,Saint-Denis,France,Brazil,0,3,France,,3,3

10) Mostre todos os jogos que terminaram em zero a zero (0 x 0).

In [ ]:
jogos['gols_na_partida'] = (jogos['HomeGoals'] + jogos['AwayGoals'])
jogos.loc[jogos['gols_na_partida'] == 0]

,Year,Date,Time,Round,Stadium,City,Country,HomeTeam,HomeGoals,AwayGoals,AwayTeam,Observation,saldo_de_gols,gols_na_partida
109,1958,1958-06-11,19:00,Group 4,Nya Ullevi,Gothenburg,Sweden,Brazil,0,0,England,,0,0
117,1958,1958-06-15,14:00,Group 3,Rasunda Stadium,Solna,Sweden,Sweden,0,0,Wales,,0,0
143,1962,1962-05-31,15:00,Group 2,Nacional,Santiago De Chile,Chile,Germany FR,0,0,Italy,,0,0
145,1962,1962-06-02,15:00,Group 3,Estadio Sausalito,Vina Del Mar,Chile,Brazil,0,0,Czechoslovakia,,0,0
154,1962,1962-06-06,15:00,Group 4,Estadio El Teniente-Codelco,Rancagua,Chile,Hungary,0,0,Argentina,,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
815,2014,2014-06-25,17:00,Group E,Estadio do Maracana,Rio De Janeiro,Brazil,Ecuador,0,0,France,,0,0
829,2014,2014-07-09,17:00,Semi-finals,Arena de Sao Paulo,Sao Paulo,Brazil,Netherlands,0,0,Argentina,Argentina win on penalties (2 - 4),0,0
830,2014,2014-07-05,17:00,Quarter-finals,Arena Fonte Nova,Salvador,Brazil,Netherlands,0,0,Costa Rica,Netherlands win on penalties (4 - 3),0,0
847,2014,2014-07-05,17:00,Quarter-finals,Arena Fonte Nova,Salvador,Brazil,Netherlands,0,0,Costa Rica,Netherlands win on penalties (4 - 3),0,0
849,2014,2014-07-09,17:00,Semi-finals,Arena de Sao Paulo,Sao Paulo,Brazil,Netherlands,0,0,Argentina,Argentina win on penalties (2 - 4),0,0